name: Build with PyInstaller

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: 拉取代码
        uses: actions/checkout@v5

      - name: 配置Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'

      - name: 安装依赖
        run: |
          pip install pyinstaller
          pip install -r requirements.txt

      - name: 开始构建
        run: pyinstaller --noconsole --name OakStore main.py

      - name: 上传
        uses: actions/upload-artifact@v5
        with:
          name: Windows-amd64
          path: dist/
